services:
  doclayout:
    container_name: doclayout
    image: ultralytics/ultralytics:latest
    
    ipc: host
    network_mode: "bridge"
    stdin_open: true
    tty: true
    
    volumes:
      - .:/workspace
      - 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
